name: Bug report
description: Create a report to help Termix improve
title: "[BUG]"
labels: [bug]
assignees: []
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Brief, descriptive title for the bug
      placeholder: "Brief description of the bug"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: How are you using Termix?
      options:
        - Website - Firefox
        - Website - Safari
        - Website - Chrome
        - Website - Other Browser
        - App - Windows
        - App - Linux
        - App - iOS
        - App - Android
        - Documentation
        - N/A
    validations:
      required: true
  - type: dropdown
    id: server-installation-method
    attributes:
      label: Server Installation Method
      description: How is the Termix server installed?
      options:
        - Docker
        - Manual Build
        - N/A
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Find your version in the User Profile tab
      placeholder: "e.g., 1.7.0"
    validations:
      required: true
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: Please check all that apply
      options:
        - label: I have examined logs and tried to find the issue
        - label: I have reviewed opened and closed issues
        - label: I have tried restarting the application
  - type: textarea
    id: problem-description
    attributes:
      label: The Problem
      description: Describe the bug in detail. Include as much information as possible with screenshots if applicable.
      placeholder: "Describe what went wrong..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to Reproduce
      description: Use as few steps as possible to reproduce the issue
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other context about the problem here..."
